import { prisma } from './prisma';
import { UnitOfWork } from '../repositories/implements/uow.repository';
import { UserService } from '../services/user.service';
import { ProductService } from '../services/product.service';
import { ShopService } from '../services/shop.service';
import { KycService } from '../services/kyc.service';
import { PermissionService } from '../services/permissions.service';
import { RoleService } from '../services/role.service';
import { CartService } from '../services/cart.service';
import { OrderService } from '../services/order.service';
import { PaymentService } from '../services/payment.service';
import { CashbackService } from '../services/cashback.service';
import { CashbackCronService } from '../services/cashback-cron.service';
import { BlockchainService } from '../services/blockchain.service';
import { AuthService } from '../services/auth.service';
import { AdminService } from '../services/admin.service';
import { CategoryService } from '../services/category.service';
import { ConversationService } from '../services/conversation.service';
import { MessageService } from '../services/message.service';
import { VNPayService } from '../services/vnpay.service';
import { VoucherService } from '../services/voucher.service';

const unitOfWork = new UnitOfWork(prisma);
export const uow = unitOfWork;
export const adminService = new AdminService(unitOfWork);
export const authService = new AuthService(unitOfWork);
export const permissionService = new PermissionService();
export const userService = new UserService(unitOfWork);
export const productService = new ProductService(unitOfWork);
export const shopService = new ShopService(unitOfWork);
export const kycService = new KycService(unitOfWork);
export const roleService = new RoleService(unitOfWork);
export const cartService = new CartService(unitOfWork);
export const orderService = new OrderService(unitOfWork);
export const paymentService = new PaymentService(unitOfWork);
export const blockchainService = new BlockchainService();
export const cashbackService = new CashbackService(unitOfWork, blockchainService);
export const cashbackCronService = new CashbackCronService(cashbackService, paymentService);
export const categoryService = new CategoryService(unitOfWork);
export const conversationService = new ConversationService(unitOfWork);
export const messageService = new MessageService(unitOfWork);
export const vnpayService = new VNPayService(unitOfWork);
export const voucherService = new VoucherService(unitOfWork);